### ISSUE TITLE
买花盆和手套

### ISSUE THREAD

**Issue by suzumi233** [Duke-Suzumi-cp/our-home#3]
@a22002020 记得从豪德寺下车买

- [x] 花盆
- [x] 指套
- [x] 大剪刀
- [x] 纸巾

**Comment by suzumi233** [comment]
why cant assign any tags or persons

**Comment by a22002020** [comment]
> why cant assign any tags or persons

没权限？

**Comment by a22002020** [comment]
给了owner权限

**Comment by a22002020** [comment]
买完了
